#!/bin/bash

calendarl() {
    LOCK_FILE_CALENDAR="$HOME/.cache/eww-calendar.lock"
    EWW_BIN=$(which eww)

run() {
    ${EWW_BIN} open calendar -c $HOME/.config/eww/Calendar/ 
}

# Open widgets
if [[ ! -f "$LOCK_FILE_CALENDAR" ]]; then
    ${EWW_BIN} close calendar -c $HOME/.config/eww/Calendar/
    touch "$LOCK_FILE_CALENDAR"
    run && echo "ok good!"
elif [[ -f "$LOCK_FILE_CALENDAR" ]]; then
    ${EWW_BIN} close calendar -c $HOME/.config/eww/Calendar/
    rm "$LOCK_FILE_CALENDAR" && echo "closed"
fi
}

calendarl
